openapi: "3.0.1"
info:
  version: 0.0.1
  description: User app to register and verify users
paths:
  /register:
    post:
      operationId: registerUser
      responses:
        default:
          description: "Default response for POST /register"
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/registerUser'

components:
  x-amazon-apigateway-integrations:
    registerUser:
      type: AWS_PROXY
      httpMethod: POST
      uri: "${register_user_function_arn}"
      payloadFormatVersion: "2.0"