name: Deploy Infra to dev environment

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::160071257600:role/iac-serverless-github-actions-role

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: login-aws, lint, security check
        uses: raj7A/iac-serverless/.github/tf_apply_pre_steps@main
        with:
          AWS_REGION       : ${{ env.AWS_REGION }}
          IAM_ROLE         : ${{ env.IAM_ROLE }}

      - name: Terraform create plan
        run: |
          terraform init
          terraform plan -var-file="dev.tfvars"

      - name: Terraform create
        run: |
          terraform apply --auto-approve -var-file="dev.tfvars"
