name: Deploy Infra to dev environment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::160071257600:role/iac-serverless-raj-github-actions-role

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: login-aws, format, lint, security check
        uses: raj7A/iac-serverless/.github/tf_apply_pre_steps@main
        with:
          AWS_REGION       : ${{ env.AWS_REGION }}
          IAM_ROLE         : ${{ env.IAM_ROLE }}

      - name: Terraform apply plan
        run: |
          terraform plan --var-file=environments/dev.tfvars

      - name: Terraform apply
        run: |
          terraform apply --auto-approve --var-file=environments/dev.tfvars
