name: Deploy Infra

on: workflow_dispatch

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::160071257600:role/iac-serverless-raj-github-actions-role

permissions:
  id-token: write
  contents: read

jobs:
  deploy-main:
    permissions:
      id-token: write
      contents: read
    uses: raj7A/iac-serverless/.github/workflows/terraform_deploy_workflow.yaml@main
    with:
      working-directory: "."
      tf-parameters    : "-var-file=dev.tfvars"