name: Destroy Infra from dev environment

on: workflow_dispatch

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::160071257600:role/iac-serverless-raj-github-actions-role

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: login-aws, format, lint, security check
        uses: raj7A/iac-serverless/.github/tf_apply_pre_steps@main
        with:
          AWS_REGION       : ${{ env.AWS_REGION }}
          IAM_ROLE         : ${{ env.IAM_ROLE }}

      - name: Terraform destroy plan
        run: |
          terraform plan -destroy --var-file=environments/dev.tfvars

      - name: Terraform destroy
        run: |
          terraform destroy --auto-approve --var-file=environments/dev.tfvars
