name: Destroy Infra

on: workflow_dispatch

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::160071257600:role/iac-lab-raj-github-actions-role

jobs:

  destroy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform init & plan for main resources
        run: |
          terraform init
          terraform plan -destroy -var-file="dev.tfvars"

      - name: Terraform destroy for main resources
        run: |
          terraform destroy --auto-approve -var-file="dev.tfvars"
